# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TriadJUG (Java User Group)

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Meetups

description: Java User Group for the NC Piedmont Triad (Greensboro, Winston-Salem, High Point) and surrounding areas.
  

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://triadjug.org" 

#These settings might be able to go?
author: Gian Uy
twitter_username: gianuy
github_username:  gianuy
company_name: TriadJUG

jquery_v3_url: "https://code.jquery.com/jquery-3.1.0.slim.min.js"
jquery_v2_url: "https://code.jquery.com/jquery-2.2.4.min.js"

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

